#!/bin/bash

echo '# DO NOT EDIT THIS FILE! It is automatically generated.'
while read line; do
  if [[ "${line}" =~ ^@@IMPORT\  ]]; then
    cat $(echo ${line} | cut -f2 -d' ')
  else
    echo ${line}
  fi
done
